language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn build
  - yarn test
